INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('명상','미라클모닝', '2021-10-29', '명상을 할 조용한 장소','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('확언하기','미라클모닝', '2021-10-29', '오늘 작성한 긍정적인 확신의 말','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('시각화','미라클모닝', '2021-10-29', '비전보드 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('감사한 일 쓰기','미라클모닝', '2021-10-29', '오늘의 감사한 내용','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('다이어리 작성','미라클모닝', '2021-10-29', '오늘 작성한 다이어리','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침에 물 한잔 마시기','생활', '2021-10-29', '물컵/물병을 들고있는 손','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('침구정리','생활', '2021-10-29', '정돈된 침대/잠자리','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('영양제 챙겨 먹기','생활', '2021-10-29', '손에 들고 있는 영양제','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침밥 챙겨 먹기','생활', '2021-10-29', '오늘 먹은 아침','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('환기하기','생활', '2021-10-29', '환기 중인 창문','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('밤 정리하기','생활', '2021-10-29', '깨끗한 방 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('모닝커피 마시기','생활', '2021-10-29', '오늘 마신 커피 한 잔','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('샤워하기','생활', '2021-10-29', '샤워 후 물에 젖은 머리','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('스트레칭','건강', '2021-10-29' , '','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('요가','건강', '2021-10-29', '요가 매트에 서 있는 발 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('산책하기','건강', '2021-10-29', '러닝화를 신은 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('러닝','건강', '2021-10-29', '러닝화를 신은 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('수면 일기 작성하기','건강', '2021-10-29', '오늘 작성한 수면 일기','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('독서','자기개발', '2021-10-29', '오늘 읽은 페이지의 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('단어 외우기','자기개발', '2021-10-29', '목표 단어 손으로 5번씩 따라적은 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('블로그 글 쓰기','자기개발', '2021-10-29', '당일 작성한 블로그 글 화면','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('뉴스 읽기','자기개발', '2021-10-29', '오늘 읽은 신문/뉴스 화면','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 4시 일어나기','기상', '2021-10-29', '','04:00', '04:10');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 5시 일어나기','기상', '2021-10-29', '','05:00', '05:10');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 6시 일어나기','기상', '2021-10-29', '','06:00', '06:10');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 7시 일어나기','기상', '2021-10-29', '','07:00', '07:10');

INSERT INTO SAYING (content) VALUES ('새로운 일을 시작하는 용기속에 당신의 천재성, 능력과 기적이 모두 숨어 있다.');
INSERT INTO SAYING (content) VALUES ('일찍 일어나는 새가 벌레를 잡아 먹는다.');
INSERT INTO SAYING (content) VALUES ('아침에 눈을 뜨자.');
INSERT INTO SAYING (content) VALUES ('이불을 개라.');