INSERT INTO ORGANIZATION (title,category,summary) VALUES ('명상','미라클모닝','오늘도 나만의 중심을 단단하게 다져보세요');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('확언하기','미라클모닝','나 자신에 대한 자신감과 확신을 일깨우는 목표를 읽어보세요.');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('시각화','미라클모닝','눈을 감고 당신이 그리는 미래를 생생하게 떠올려보세요. ');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('감사한 일 쓰기','미라클모닝','감사한 기억, 자랑스러운 성취, 소중한 대상들을 떠올리며 적어보세요.');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('다이어리 작성','미라클모닝','오늘 할 일, 어제에 대한 성찰 등 그 무엇이든 좋아요.');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('아침에 물 한잔 마시기','생활','발끝까지 깨워주는 아침 물 한잔 🥛');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('침구정리','생활','하루를 시작하는 나만의 출발선!');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('영양제 챙겨 먹기','생활','내 건강은 내가 챙겨요');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('아침밥 챙겨 먹기','생활','든든한 아침밥은 에너지의 원천입니다');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('환기하기','생활','아침의 공기로 방 안을 가득 채우세요');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('밤 정리하기','생활','나를 소중히 여기는 작고 가벼운 습관');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('모닝커피 마시기','생활','아침의 피로를 한번에 날려보세요 ☕️');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('샤워하기','생활','몸과 마음의 긴장을 풀어주는 가장 간단한 방법 🚿');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('스트레칭','건강','팔 다리 쭉쭉! 발끝까지 펴지는 시원함을 느껴봐요');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('요가','건강','매 동작과 호흡에 집중하며 수련하는 시간입니다');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('산책하기','건강','여유롭게 동네 한바퀴');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('러닝','건강','폐를 가득 채우는 시원한 아침 공기 🏃🏻‍♀️');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('수면 일기 작성하기','건강','성공적인 미라클 모닝은 양질의 수면으로부터 시작합니다');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('독서','자기개발','한 페이지씩 채우는 마음의 자양분');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('30분 자기개발','자기개발','내가 원하는 나의 모습을 만나기 위한 30분');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('단어 외우기','자기개발','티끌 모아 태산! 오늘부터 시작해보는건 어때요?');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('블로그 글 쓰기','자기개발','나의 깊이를 쌓고 싶다면, 아침 시간을 활용해 보세요');
INSERT INTO ORGANIZATION (title,category,summary) VALUES ('뉴스 읽기','자기개발','더 넓은 세상으로 나아갈 나를 위하여 🌏');
INSERT INTO SAYING (content) VALUES ('새로운 일을 시작하는 용기속에 당신의 천재성, 능력과 기적이 모두 숨어 있다.');
INSERT INTO SAYING (content) VALUES ('일찍 일어나는 새가 벌레를 잡아 먹는다.');
INSERT INTO SAYING (content) VALUES ('아침에 눈을 뜨자.');
INSERT INTO SAYING (content) VALUES ('이불을 개라.');