INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('명상','미라클모닝', '2021-10-29', '명상을 할 조용한 장소','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('확언하기','미라클모닝', '2021-10-29', '오늘 작성한 긍정적인 확신의 말','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('시각화','미라클모닝', '2021-10-29', '비전보드 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('감사한 일 쓰기','미라클모닝', '2021-10-29', '오늘의 감사한 내용','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('다이어리 작성','미라클모닝', '2021-10-29', '오늘 작성한 다이어리','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침에 물 한잔 마시기','생활', '2021-10-29', '물컵/물병을 들고있는 손','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('침구정리','생활', '2021-10-29', '정돈된 침대/잠자리','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('영양제 챙겨 먹기','생활', '2021-10-29', '손에 들고 있는 영양제','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침밥 챙겨 먹기','생활', '2021-10-29', '오늘 먹은 아침','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('환기하기','생활', '2021-10-29', '환기 중인 창문','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('밤 정리하기','생활', '2021-10-29', '깨끗한 방 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('모닝커피 마시기','생활', '2021-10-29', '오늘 마신 커피 한 잔','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('샤워하기','생활', '2021-10-29', '샤워 후 물에 젖은 머리','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('스트레칭','건강', '2021-10-29' , '','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('요가','건강', '2021-10-29', '요가 매트에 서 있는 발 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('산책하기','건강', '2021-10-29', '러닝화를 신은 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('러닝','건강', '2021-10-29', '러닝화를 신은 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('수면 일기 작성하기','건강', '2021-10-29', '오늘 작성한 수면 일기','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('독서','자기개발', '2021-10-29', '오늘 읽은 페이지의 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('단어 외우기','자기개발', '2021-10-29', '목표 단어 손으로 5번씩 따라적은 사진','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('블로그 글 쓰기','자기개발', '2021-10-29', '당일 작성한 블로그 글 화면','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('뉴스 읽기','자기개발', '2021-10-29', '오늘 읽은 신문/뉴스 화면','05:00', '08:00');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 4시 일어나기','기상', '2021-10-29', '','04:00', '04:10');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 5시 일어나기','기상', '2021-10-29', '','05:00', '05:10');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 6시 일어나기','기상', '2021-10-29', '','06:00', '06:10');
INSERT INTO ORGANIZATION (title,category ,updated_at, shoot, begin_time, end_time) VALUES ('아침 7시 일어나기','기상', '2021-10-29', '','07:00', '07:10');

INSERT INTO SAYING (content) VALUES ('성숙하다는 것은 다가오는 모든 생생한 위기를 피하지 않고 마주하는 것을 의미한다');
INSERT INTO SAYING (content) VALUES ('인생의 비극이란 사람들이 삶을 사는 동안 내면에서 잃어가는 것들이다');
INSERT INTO SAYING (content) VALUES ('우리가 노력 없이 얻는 거의 유일한 것은 노년이다');
INSERT INTO SAYING (content) VALUES ('젊음은 알지 못한 것을 탄식하고 나이는 하지 못한 것을 탄식한다');
INSERT INTO SAYING (content) VALUES ('인생에는 서두르는 것 말고도 더 많은 것이 있다');
INSERT INTO SAYING (content) VALUES ('어진 사람을 보면 그와 같이 되기를 생각하고 어질지 않은 사람을 보면 속으로 스스로 반성하라');
INSERT INTO SAYING (content) VALUES ('인간은 선천적으로는 거의 비슷하나 후천적으로 큰 차이가 나게 된다');
INSERT INTO SAYING (content) VALUES ('인간사에는 안정된 것이 하나도 없음을 기억하라');
INSERT INTO SAYING (content) VALUES ('므로 성공에 들뜨거나 역경에 지나치게 의기소침하지 마라');
INSERT INTO SAYING (content) VALUES ('인내할 수 있는 사람은 그가 바라는 것은 무엇이든지 손에 넣을 수 있다');
INSERT INTO SAYING (content) VALUES ('이 순간 살아 있으매 모든 삶의 축복에 대한 경외심을 느끼곤 합니다');
INSERT INTO SAYING (content) VALUES ('목적없는 공부는 기억에 해가 될 뿐이며 머리속에 들어온 어떤 것도 간직하지 못한다');
INSERT INTO SAYING (content) VALUES ('교육의 위대한 목표는 앎이 아니라 행동이다');
INSERT INTO SAYING (content) VALUES ('강력한 이유는 강력한 행동을 낳는다');
INSERT INTO SAYING (content) VALUES ('어려운 직업에서 성공하려면 자신을 굳게 믿어야 한다');
INSERT INTO SAYING (content) VALUES ('들은 것은 잊어버리고 본 것은 기억하고 직접 해본 것은 이해한다');
INSERT INTO SAYING (content) VALUES ('자신의 가족을 가르칠 수 없는 자는 남을 가르칠 수 없다');
INSERT INTO SAYING (content) VALUES ('인생에서 가장 위대한 교훈은 심지어는 바보도 어떨 때는 옳다는 걸 아는 것이다');
INSERT INTO SAYING (content) VALUES ('교육은 암기를 얼마나 열심히 했는지 혹은 얼마나 많이 아는지가 아니다 교육은 아는 것과 모르는 것을 구분할 줄 아는 능력이다');
INSERT INTO SAYING (content) VALUES ('우리가 해야할 일은 끊임없이 호기심을 갖고 새로운 생각을 시험해보고 새로운 인상을 받는 것이다');
INSERT INTO SAYING (content) VALUES ('이해하려고 노력하는 행동이 미덕의 첫 단계이자 유일한 기본이다');
INSERT INTO SAYING (content) VALUES ('교육은 일종의 계속되는 대화이고 그 대화는 세상일이 보통 그렇듯 여러 가지 관점이 있음을 인정한다');
INSERT INTO SAYING (content) VALUES ('학생이 되기를 멈춘 자는 한 번도 학생인 적이 없었던 자이다');
INSERT INTO SAYING (content) VALUES ('당신의 행복은 무엇이 당신의 영혼을 노래하게 하는가에 따라 결정된다');
INSERT INTO SAYING (content) VALUES ('신중하지 않으면 찾아온 기회를 놓치기 일쑤이다');
INSERT INTO SAYING (content) VALUES ('인생에서 실패한 사람 중 다수는 성공을 목전에 두고도 모른 채 포기한 이들이다');
INSERT INTO SAYING (content) VALUES ('성공은 영원하지 않고 실패는 치명적이지 않다');
INSERT INTO SAYING (content) VALUES ('성공한 사람보다는 가치 있는 사람이 되려 하라');
INSERT INTO SAYING (content) VALUES ('인생에 있는 큰 비밀은 큰 비밀 따위는 없다는 것이다 당신의 목표가 무엇이든 열심히 할 의지가 있다면 달성할 수 있다');
INSERT INTO SAYING (content) VALUES ('문제는 어떻게 새롭고 혁신적인 생각을 하느냐가 아니라 어떻게 오래된 생각을 비워내느냐 하는 것이다');
INSERT INTO SAYING (content) VALUES ('승자들은 자신이 어디로 가고 있는지 그 길을 가면서 무엇을 할 계획인지 그 모험을 누구와 함께 할 것인지 말할 수 있다');
INSERT INTO SAYING (content) VALUES ('한 권의 책을 읽음으로써 자신의 삶에서 새 시대를 본 사람이 너무나 많다');
INSERT INTO SAYING (content) VALUES ('독서할 때 당신은 항상 가장 좋은 친구와 함께 있다');
INSERT INTO SAYING (content) VALUES ('한 문장이라도 매일 조금씩 읽기로 결심하라 하루 15분씩 시간을 내면 연말에는 변화가 느껴질 것이다');
INSERT INTO SAYING (content) VALUES ('긴 하루 끝에 좋은 책이 기다리고 있다는 생각만으로 그날은 더 행복해진다');
INSERT INTO SAYING (content) VALUES ('시간은 우리를 변화시키지 않는다 시간은 단지 우리를 펼쳐 보일 뿐이다');
INSERT INTO SAYING (content) VALUES ('미래는 현재 우리가 무엇을 하는가에 달려 있다');
INSERT INTO SAYING (content) VALUES ('경험을 현명하게 사용한다면 어떤 일도 시간 낭비는 아니다');
INSERT INTO SAYING (content) VALUES ('일 분 전만큼 먼 시간은 없다');
INSERT INTO SAYING (content) VALUES ('시간은 인생의 동전이다 시간은 네가 가진 유일한 동전이고 그 동전을 어디에 쓸지는 너만이 결정할 수 있다');
INSERT INTO SAYING (content) VALUES ('과거를 기억 못하는 이들은 과거를 반복하기 마련이다');
INSERT INTO SAYING (content) VALUES ('우리가 계획한 삶을 기꺼이 버릴 수 있을 때만 우리를 기다리고 있는 삶을 맞이할 수 있다');
INSERT INTO SAYING (content) VALUES ('수정을 용납하지 않는 계획은 나쁜 계획이다');
INSERT INTO SAYING (content) VALUES ('매일 아침 하루 일과를 계획하고 그 계획을 실행하는 사람은 극도로 바쁜 미로 같은 삶 속에서 그를 안내할 한 올의 실을 지니고 있는 것이다');
INSERT INTO SAYING (content) VALUES ('현재가 과거와 다르길 바란다면 과거를 공부하라');
INSERT INTO SAYING (content) VALUES ('지금 적극적으로 실행되는 괜찮은 계획이 다음 주의 완벽한 계획보다 낫다');
INSERT INTO SAYING (content) VALUES ('성공하려고 아무리 열심히 노력해도 실패에 대한 두려움이 마음에 가득하다면 성공은 불가능해질 것이다');
INSERT INTO SAYING (content) VALUES ('이 순간 최선을 다하면 다음 순간에 최고의 자리에 오를 수 있다');
INSERT INTO SAYING (content) VALUES ('피울 수 있을 만큼 똑똑하지 못한 것을 포부가 높기 때문이라고 변명할 수 없다');
INSERT INTO SAYING (content) VALUES ('지식이 없는 성실은 허약하고 쓸모 없다 성실이 없는 지식은 위험하고 두려운 것이다');
INSERT INTO SAYING (content) VALUES ('이 세상의 유일한 악마는 우리 마음에서 날뛰고 있기에 모든 전투를 마음 속에서 싸워야 한다');
INSERT INTO SAYING (content) VALUES ('큰 희망이 큰 사람을 만든다');
INSERT INTO SAYING (content) VALUES ('어떤 일을 하기에 앞서 스스로 그 일에 대한 기대를 가져야 한다');
INSERT INTO SAYING (content) VALUES ('인류에게는 정말로 효과적인 무기가 하나있다 바로 웃음이다');
INSERT INTO SAYING (content) VALUES ('못 가진 것에 대한 욕망으로 가진 것을 망치지 말라 하지만 지금 가진 것이 한때는 바라기만 했던 것 중 하나였다는 것도 기억하라');
INSERT INTO SAYING (content) VALUES ('희망은 밝고 환한 양초 불빛처럼 우리 인생의 행로를 장식하고 용기를 준다 밤의 어둠이 짙을수록 그 빛은 더욱 밝다');
INSERT INTO SAYING (content) VALUES ('우리가 무슨 생각을 하느냐가 우리가 어떤 사람이 되는지를 결정한다');
INSERT INTO SAYING (content) VALUES ('가장 현명한 사람은 자신만의 방향을 따른다');
INSERT INTO SAYING (content) VALUES ('난관은 낙담이 아닌 분발을 위한 것이다 인간의 정신은 투쟁을 통해 강해진다');
INSERT INTO SAYING (content) VALUES ('우리가 바로 이 시대의 유행이기 때문에 우리 자신으로부터 탈피할 수 없다');
INSERT INTO SAYING (content) VALUES ('다른 이들의 말 그들의 목소리에 더 이상 신경쓰지 마라 세상에서 가장 어려운 것에 도전하라 스스로 행동하라 진실을 대면하라');
INSERT INTO SAYING (content) VALUES ('열정없이 사느니 차라리 죽는게 낫다');
INSERT INTO SAYING (content) VALUES ('계산된 위험은 감수하라 이는 단순히 무모한 것과는 완전히 다른 것이다');
INSERT INTO SAYING (content) VALUES ('마음을 위대한 일로 이끄는 것은 오직 열정 위대한 열정뿐이다');
INSERT INTO SAYING (content) VALUES ('하늘을 날고 싶은 충동을 느낄 때 결코 땅을 기라는데 동의할 수는 없다');
INSERT INTO SAYING (content) VALUES ('가장 큰 위험은 위험없는 삶이다');
INSERT INTO SAYING (content) VALUES ('여러분이 할 수 있는 가장 큰 모험은 바로 여러분이 꿈꿔오던 삶을 사는 것입니다');
INSERT INTO SAYING (content) VALUES ('어디를 가든지 마음을 다해 가라');
INSERT INTO SAYING (content) VALUES ('천재성에는 한계가 있을 수 있지만 어리석음에는 이런 장애가 없다');
INSERT INTO SAYING (content) VALUES ('약간의 광기를 띠지 않은 위대한 천재란 없다');
INSERT INTO SAYING (content) VALUES ('만족은 결과가 아니라 과정에서 온다');
INSERT INTO SAYING (content) VALUES ('내 자신에 대한 자신감을 잃으면 온 세상이 나의 적이 된다');
INSERT INTO SAYING (content) VALUES ('가장 용감한 행동은 자신만을 생각하는 것이다 큰 소리로');
INSERT INTO SAYING (content) VALUES ('흠집 없는 조약돌보다는 흠집 있는 다이아몬드가 낫다');
INSERT INTO SAYING (content) VALUES ('쉬운 일을 어려운 일처럼 어려운 일을 쉬운 일처럼 대하라 전자는 자신감이 잠들지 않게 후자는 자신감을 잃지 않기 위함이다');
INSERT INTO SAYING (content) VALUES ('공은 아무 것도 아닌 그저 우연에 불과하다 그러나 자신에 대한 확신을 갖는 것은 이와는 확실히 다르다');
INSERT INTO SAYING (content) VALUES ('우리가 어떤 일을 감히 하지 못하는 것은 그 일이 너무 어렵기 때문이 아니라 어렵다는 생각에 사로잡혀 그 일을 시도하지 않기 때문이다');
INSERT INTO SAYING (content) VALUES ('우리의 내일은 오늘 무슨 생각을 하느냐에 달려 있다');
INSERT INTO SAYING (content) VALUES ('믿음은 강력한 영향력을 행사한다 우리의 뇌는 우리가 믿고 기대하는 방향으로 작동한다');
INSERT INTO SAYING (content) VALUES ('우리는 우리가 행복해지려고 마음먹은 만큼 행복해질 수 있다 행복해지고 싶으면 행복하다고 생각하라');
INSERT INTO SAYING (content) VALUES ('세상에는 두 종류의 사람이 존재한다 변명하는 사람과 결과를 얻는 사람이 바로 그것이다');
INSERT INTO SAYING (content) VALUES ('태도는 사소한 것이지만 그것이 만드는 차이는 엄청나다 즉 어떤 마음가짐을 갖느냐가 어떤 일을 하느냐보다 더 큰 가치를 만들 수 있다');
INSERT INTO SAYING (content) VALUES ('다수의 사람들은 장애물을 보지만 소수의 사람들은 목표를 본다 역사는 후자의 성공을 기록한다');
INSERT INTO SAYING (content) VALUES ('삶이란 우리의 인생 앞에 어떤 일이 생기느냐에 따라 결정되는 것이 아니라 우리가 어떤 태도를 취하느냐에 따라 결정된다');
INSERT INTO SAYING (content) VALUES ('비관론자들은 모든 기회에 숨어 있는 문제를 보고 낙관론자들은 모든 문제에 감추어져 있는 기회를 본다');
INSERT INTO SAYING (content) VALUES ('불가능 그것은 나약한 사람들의 핑계에 불과하다');
INSERT INTO SAYING (content) VALUES ('어떤 일을 시작하면 일단 잘될 것이라고 낙관하라 그러면 그 낙관론이 성공을 안겨줄 것이다');
INSERT INTO SAYING (content) VALUES ('햇빛이 비치는 곳이면 어디든 그늘이 있고 빛이 있는 곳이면 어두움이 있게 마련이다');
INSERT INTO SAYING (content) VALUES ('인간이 할 수 있는 일이라면 무엇이나 할 수 있다는 마음만 갖는다면 설사 어떤 고난에 처한다 해도 언젠가는 반드시 목표를 달성할 수 있다');
INSERT INTO SAYING (content) VALUES ('리더들이 제일 먼저 극복한 것은 외부적인 것이 아니라 나는 못한다 나는 재능이 없다 내가 해서는 안 된다’는 두려움이었다');
INSERT INTO SAYING (content) VALUES ('운명은 용기 있는 사람 앞에서는 약하고 비겁한 사람 앞에서는 강하다');
INSERT INTO SAYING (content) VALUES ('생각을 먼저 지배하는 것은 우리들이지만 그 다음에는 생각이 우리를 지배한다');
INSERT INTO SAYING (content) VALUES ('마음은 수천 개의 채널이 있는 텔레비전과 같다 그리하여 우리가 선택하는 채널대로 순간순간의 우리가 존재하게 된다');
INSERT INTO SAYING (content) VALUES ('길을 걷다가 돌을 보면 약자는 그것을 걸림돌이라고 하고 강자는 그것을 디딤돌이라고 한다');
INSERT INTO SAYING (content) VALUES ('나 자신에 대한 자신감을 잃으면 온 세상이 나의 적이 된다');
INSERT INTO SAYING (content) VALUES ('승리할 것이라고 생각하면 승리할 수 있다 자신감이야말로 승리의 조건이다');
INSERT INTO SAYING (content) VALUES ('노력없이 쓰인 글은 대개 감흥없이 읽힌다');
INSERT INTO SAYING (content) VALUES ('나는 실패한 적이 없다 그저 작동하지 않는 10000개의 방법을 발견했을 뿐이다');
INSERT INTO SAYING (content) VALUES ('성공이란 열정을 잃지 않고 실패를 거듭할 수 있는 능력이다');
INSERT INTO SAYING (content) VALUES ('성공의 크기는 열망의 깊이에 좌우된다');
INSERT INTO SAYING (content) VALUES ('해보지 않고는 당신이 무엇을 해낼 수 있는지 알 수 없다');